import 'package:career_buddy_lms/features/generic_writing/domain/services/writing_summary_parser.dart';
import 'package:flutter_test/flutter_test.dart';

// Exact block shapes generated by `submit_exercise`
// (`activities/views.py:1465-1495`) — single-quoted class attributes,
// verbatim.
const _taskWithIssues =
    "<div class='mt-3 mb-2 text-start'><strong>Task 1:</strong></div>"
    "<ul class='text-start ps-4' style='font-size: 0.9em;'>"
    "<li class='mb-2'><strong><span class='text-danger'>very good</span></strong>: Overused phrase "
    "<br><span class='text-success'>Suggestion: excellent</span></li>"
    "</ul>"
    "<div class='p-3 bg-light border rounded text-start mt-2' style='font-size: 0.9em; white-space: pre-wrap;'>"
    "<strong>Improved Version:</strong><br>This is the improved passage.</div>";

const _taskNoIssues =
    "<div class='mt-3 mb-2 text-start'><strong>Task 2:</strong></div>"
    "<div class='text-success text-start mb-2 ps-2'><i class='fas fa-check-circle me-1'></i>No major issues found.</div>";

const _taskTooShort =
    "<div class='mt-3 mb-2 text-danger text-start'><strong>Task 3:</strong> Answer too short to evaluate.</div>";

void main() {
  group('parseWritingSummaryHtml', () {
    test('an empty string parses to an empty list', () {
      expect(parseWritingSummaryHtml(''), isEmpty);
    });

    test('a task with issues extracts phrase/message/suggestion and the improved passage', () {
      final result = parseWritingSummaryHtml(_taskWithIssues);

      expect(result, hasLength(1));
      expect(result.single.taskNumber, 1);
      expect(result.single.tooShortToEvaluate, isFalse);
      expect(result.single.issues, hasLength(1));
      expect(result.single.issues.single.phrase, 'very good');
      expect(result.single.issues.single.message, 'Overused phrase');
      expect(result.single.issues.single.suggestion, 'excellent');
      expect(result.single.improvedPassage, 'This is the improved passage.');
    });

    test('a task with no issues has an empty issues list and no improved passage', () {
      final result = parseWritingSummaryHtml(_taskNoIssues);

      expect(result, hasLength(1));
      expect(result.single.taskNumber, 2);
      expect(result.single.tooShortToEvaluate, isFalse);
      expect(result.single.issues, isEmpty);
      expect(result.single.improvedPassage, isNull);
    });

    test('a too-short task is flagged and carries no issues/improved passage', () {
      final result = parseWritingSummaryHtml(_taskTooShort);

      expect(result, hasLength(1));
      expect(result.single.taskNumber, 3);
      expect(result.single.tooShortToEvaluate, isTrue);
      expect(result.single.issues, isEmpty);
      expect(result.single.improvedPassage, isNull);
    });

    test('all three block shapes concatenated (the real "".join(ai_feedbacks) shape) parse in order', () {
      final html = _taskWithIssues + _taskNoIssues + _taskTooShort;
      final result = parseWritingSummaryHtml(html);

      expect(result.map((t) => t.taskNumber), [1, 2, 3]);
      expect(result[0].issues, hasLength(1));
      expect(result[1].issues, isEmpty);
      expect(result[2].tooShortToEvaluate, isTrue);
    });

    test('a task entirely missing from the HTML (the AI call threw server-side) is simply absent, not a gap-filled entry', () {
      // Task 2 never appended by the server in this scenario
      // (`activities/views.py:1482-1484`) — only tasks 1 and 3 exist.
      final html = _taskWithIssues + _taskTooShort;
      final result = parseWritingSummaryHtml(html);

      expect(result.map((t) => t.taskNumber), [1, 3]);
    });
  });
}
